// File generated by FlutterFire CLI (run: dart run flutterfire configure)
// Replace this file by running: dart run flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this project. '
      'Run "dart run flutterfire configure" to generate firebase_options.dart',
    );
  }
}
